version: '3'

networks:
  default:

volumes:
  postgres:
  pgadmin:
  redis:

services:
  postgres:
    image: postgres:12
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 15432:80
  redis:
    image: bitnami/redis:latest
    env_file:
      - .env
    volumes:
      - redis:/bitnami/redis/data
    ports:
      - 6379:6379
