version: "3"

networks:
  default:

volumes:
  postgres:
  redis:

services: 
  authenticate:
    image: link/authenticate:latest
  shortener:
    image: link/shortener:latest
  statistics:
    image: link/statistics:latest
  postgres:
    image: postgres:12
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: bitnami/redis:latest
    environment:
      - .env
    volumes:
      - redis:/bitnami/redis/data