// Code generated by protoc-gen-go. DO NOT EDIT.
// source: link.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LinkCreateRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkCreateRequest) Reset()         { *m = LinkCreateRequest{} }
func (m *LinkCreateRequest) String() string { return proto.CompactTextString(m) }
func (*LinkCreateRequest) ProtoMessage()    {}
func (*LinkCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ee656911eb8a56a, []int{0}
}

func (m *LinkCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkCreateRequest.Unmarshal(m, b)
}
func (m *LinkCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkCreateRequest.Marshal(b, m, deterministic)
}
func (m *LinkCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkCreateRequest.Merge(m, src)
}
func (m *LinkCreateRequest) XXX_Size() int {
	return xxx_messageInfo_LinkCreateRequest.Size(m)
}
func (m *LinkCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LinkCreateRequest proto.InternalMessageInfo

func (m *LinkCreateRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *LinkCreateRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type LinkCreateResponse struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkCreateResponse) Reset()         { *m = LinkCreateResponse{} }
func (m *LinkCreateResponse) String() string { return proto.CompactTextString(m) }
func (*LinkCreateResponse) ProtoMessage()    {}
func (*LinkCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ee656911eb8a56a, []int{1}
}

func (m *LinkCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkCreateResponse.Unmarshal(m, b)
}
func (m *LinkCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkCreateResponse.Marshal(b, m, deterministic)
}
func (m *LinkCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkCreateResponse.Merge(m, src)
}
func (m *LinkCreateResponse) XXX_Size() int {
	return xxx_messageInfo_LinkCreateResponse.Size(m)
}
func (m *LinkCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LinkCreateResponse proto.InternalMessageInfo

func (m *LinkCreateResponse) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type LinkReturnRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkReturnRequest) Reset()         { *m = LinkReturnRequest{} }
func (m *LinkReturnRequest) String() string { return proto.CompactTextString(m) }
func (*LinkReturnRequest) ProtoMessage()    {}
func (*LinkReturnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ee656911eb8a56a, []int{2}
}

func (m *LinkReturnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkReturnRequest.Unmarshal(m, b)
}
func (m *LinkReturnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkReturnRequest.Marshal(b, m, deterministic)
}
func (m *LinkReturnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkReturnRequest.Merge(m, src)
}
func (m *LinkReturnRequest) XXX_Size() int {
	return xxx_messageInfo_LinkReturnRequest.Size(m)
}
func (m *LinkReturnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkReturnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LinkReturnRequest proto.InternalMessageInfo

func (m *LinkReturnRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type LinkReturnResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkReturnResponse) Reset()         { *m = LinkReturnResponse{} }
func (m *LinkReturnResponse) String() string { return proto.CompactTextString(m) }
func (*LinkReturnResponse) ProtoMessage()    {}
func (*LinkReturnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ee656911eb8a56a, []int{3}
}

func (m *LinkReturnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkReturnResponse.Unmarshal(m, b)
}
func (m *LinkReturnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkReturnResponse.Marshal(b, m, deterministic)
}
func (m *LinkReturnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkReturnResponse.Merge(m, src)
}
func (m *LinkReturnResponse) XXX_Size() int {
	return xxx_messageInfo_LinkReturnResponse.Size(m)
}
func (m *LinkReturnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkReturnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LinkReturnResponse proto.InternalMessageInfo

func (m *LinkReturnResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*LinkCreateRequest)(nil), "api.LinkCreateRequest")
	proto.RegisterType((*LinkCreateResponse)(nil), "api.LinkCreateResponse")
	proto.RegisterType((*LinkReturnRequest)(nil), "api.LinkReturnRequest")
	proto.RegisterType((*LinkReturnResponse)(nil), "api.LinkReturnResponse")
}

func init() {
	proto.RegisterFile("link.proto", fileDescriptor_2ee656911eb8a56a)
}

var fileDescriptor_2ee656911eb8a56a = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xc9, 0xcc, 0xcb,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xb2, 0xe4, 0x12, 0xf4,
	0xc9, 0xcc, 0xcb, 0x76, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0x12, 0xe0, 0x62, 0x2e, 0x2d, 0xca, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31,
	0x85, 0x84, 0xb8, 0x58, 0x8a, 0x73, 0x4a, 0xd3, 0x25, 0x98, 0xc0, 0x42, 0x60, 0xb6, 0x92, 0x06,
	0x97, 0x10, 0xb2, 0xd6, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xb8, 0x4a, 0x46, 0x24, 0x95, 0xea,
	0x10, 0x4b, 0x82, 0x52, 0x4b, 0x4a, 0x8b, 0xf2, 0x60, 0x96, 0x60, 0x53, 0xa8, 0x06, 0x31, 0x12,
	0xa6, 0x10, 0x6a, 0x24, 0x86, 0x73, 0x8c, 0x6a, 0xb8, 0x58, 0x40, 0xea, 0x84, 0x2c, 0xb9, 0xd8,
	0x20, 0xd6, 0x0b, 0x89, 0xe9, 0x25, 0x16, 0x64, 0xea, 0x61, 0x78, 0x45, 0x4a, 0x1c, 0x43, 0x1c,
	0x6a, 0xa8, 0x25, 0x17, 0x1b, 0xc4, 0x1a, 0x24, 0xad, 0x28, 0x0e, 0x44, 0xd2, 0x8a, 0xea, 0x9e,
	0x24, 0x36, 0x70, 0xf8, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x93, 0xcc, 0x98, 0x9e, 0x4d,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LinkClient is the client API for Link service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LinkClient interface {
	Create(ctx context.Context, in *LinkCreateRequest, opts ...grpc.CallOption) (*LinkCreateResponse, error)
	Return(ctx context.Context, in *LinkReturnRequest, opts ...grpc.CallOption) (*LinkReturnResponse, error)
}

type linkClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkClient(cc grpc.ClientConnInterface) LinkClient {
	return &linkClient{cc}
}

func (c *linkClient) Create(ctx context.Context, in *LinkCreateRequest, opts ...grpc.CallOption) (*LinkCreateResponse, error) {
	out := new(LinkCreateResponse)
	err := c.cc.Invoke(ctx, "/api.Link/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) Return(ctx context.Context, in *LinkReturnRequest, opts ...grpc.CallOption) (*LinkReturnResponse, error) {
	out := new(LinkReturnResponse)
	err := c.cc.Invoke(ctx, "/api.Link/Return", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkServer is the server API for Link service.
type LinkServer interface {
	Create(context.Context, *LinkCreateRequest) (*LinkCreateResponse, error)
	Return(context.Context, *LinkReturnRequest) (*LinkReturnResponse, error)
}

// UnimplementedLinkServer can be embedded to have forward compatible implementations.
type UnimplementedLinkServer struct {
}

func (*UnimplementedLinkServer) Create(ctx context.Context, req *LinkCreateRequest) (*LinkCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedLinkServer) Return(ctx context.Context, req *LinkReturnRequest) (*LinkReturnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Return not implemented")
}

func RegisterLinkServer(s *grpc.Server, srv LinkServer) {
	s.RegisterService(&_Link_serviceDesc, srv)
}

func _Link_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Link/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Create(ctx, req.(*LinkCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_Return_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkReturnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Return(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Link/Return",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Return(ctx, req.(*LinkReturnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Link_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Link",
	HandlerType: (*LinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Link_Create_Handler,
		},
		{
			MethodName: "Return",
			Handler:    _Link_Return_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "link.proto",
}
