// Code generated by protoc-gen-go. DO NOT EDIT.
// source: misc.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VoidRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoidRequest) Reset()         { *m = VoidRequest{} }
func (m *VoidRequest) String() string { return proto.CompactTextString(m) }
func (*VoidRequest) ProtoMessage()    {}
func (*VoidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d3ba2f07ad357c5, []int{0}
}

func (m *VoidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoidRequest.Unmarshal(m, b)
}
func (m *VoidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoidRequest.Marshal(b, m, deterministic)
}
func (m *VoidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoidRequest.Merge(m, src)
}
func (m *VoidRequest) XXX_Size() int {
	return xxx_messageInfo_VoidRequest.Size(m)
}
func (m *VoidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VoidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VoidRequest proto.InternalMessageInfo

type VoidResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoidResponse) Reset()         { *m = VoidResponse{} }
func (m *VoidResponse) String() string { return proto.CompactTextString(m) }
func (*VoidResponse) ProtoMessage()    {}
func (*VoidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d3ba2f07ad357c5, []int{1}
}

func (m *VoidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoidResponse.Unmarshal(m, b)
}
func (m *VoidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoidResponse.Marshal(b, m, deterministic)
}
func (m *VoidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoidResponse.Merge(m, src)
}
func (m *VoidResponse) XXX_Size() int {
	return xxx_messageInfo_VoidResponse.Size(m)
}
func (m *VoidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VoidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VoidResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*VoidRequest)(nil), "api.VoidRequest")
	proto.RegisterType((*VoidResponse)(nil), "api.VoidResponse")
}

func init() {
	proto.RegisterFile("misc.proto", fileDescriptor_2d3ba2f07ad357c5)
}

var fileDescriptor_2d3ba2f07ad357c5 = []byte{
	// 73 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcd, 0x2c, 0x4e,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xe2, 0xe5, 0xe2, 0x0e,
	0xcb, 0xcf, 0x4c, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0xe2, 0xe3, 0xe2, 0x81, 0x70,
	0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x93, 0xd8, 0xc0, 0x4a, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x3d, 0x5f, 0xd3, 0x48, 0x38, 0x00, 0x00, 0x00,
}
